version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./app:/app/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: kroops7852
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"  # Changed to use port 3307 on the host
